<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { createSpeechService } from './services/speech'

type Mastery = { mastery:number; recent_accuracy:number; effective_difficulty:number; evidence_count:number; confidence:number; pattern_coverage:number; intent_coverage:number; transfer:number; weak_subscene_count:number; state:string; last_practiced:string }
type Subscene = { id:string; name:string; description:string; mastery:Mastery }
type Scene = { id:string; name:string; description:string; category:string; mastery:Mastery; subscenes:Subscene[] }
type Exercise = { exercise_id:string; chinese_prompt:string; target_pattern:string; pattern_id:string; scene_id:string; subscene_id?:string; communication_intent:string; difficulty:number; selection_reason:string; scope_relaxed?:boolean; relaxation_reason?:string }
type Evaluation = { verdict:string; meaning_score:number; grammar_score:number; naturalness_score:number; pattern_score:number; suggested_answer:string; explanation_zh:string; errors:Array<{type:string; explanation:string}> }
type HistoryItem = { id:string; submitted_at:string; prompt:string; answer:string; verdict:string; suggested_answer:string; scene_id:string; subscene_id:string; pattern_id:string; difficulty:number }

const page = ref('practice'); const scenes = ref<Scene[]>([]); const selectedScene = ref<Scene|null>(null); const selectedSceneID = ref(''); const selectedSubsceneID = ref(''); const exercise = ref<Exercise|null>(null); const answer = ref(''); const evaluation = ref<Evaluation|null>(null); const loading = ref(false); const message = ref(''); const failedAttemptID = ref(''); const sessionID = ref(''); const mode = ref('adaptive'); const history = ref<HistoryItem[]>([]); const historyScene = ref(''); const historySubscene = ref(''); const progress = ref<Record<string,any>>({}); const reviews = ref<Array<any>>([])
const speech = createSpeechService(); const speechSupported = ref(speech.isSupported()); const lastAttemptID = ref('')
async function api<T>(url:string, init?:RequestInit):Promise<T>{ const response=await fetch(url,{headers:{'Content-Type':'application/json'},...init}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'Request failed'); return data }
async function loadScenes(){ scenes.value=await api<Scene[]>('/api/scenes') }
async function openScene(id:string){ selectedScene.value=await api<Scene>(`/api/scenes/${id}`); selectedSceneID.value=id; selectedSubsceneID.value=''; page.value='scene-detail' }
async function startPractice(sceneID=selectedSceneID.value,subsceneID=''){ selectedSceneID.value=sceneID; selectedSubsceneID.value=subsceneID; sessionID.value=''; if(sceneID){ const session=await api<{session_id:string}>('/api/sessions',{method:'POST',body:JSON.stringify({mode:'scene',scene_id:sceneID,subscene_id:subsceneID,practice_scope:subsceneID?'subscene':'scene'})}); sessionID.value=session.session_id } page.value='practice'; await nextExercise() }
async function nextExercise(){ loading.value=true; message.value=''; evaluation.value=null; failedAttemptID.value=''; answer.value=''; try{ exercise.value=await api<Exercise>('/api/practice/next',{method:'POST',body:JSON.stringify({mode:mode.value,scene_id:selectedSceneID.value,subscene_id:selectedSubsceneID.value,session_id:sessionID.value})}) }catch(error){message.value=(error as Error).message}finally{loading.value=false} }
async function submit(){ if(!exercise.value||!answer.value.trim()) return; loading.value=true; message.value=''; failedAttemptID.value=''; try{ const result=await api<{attempt_id:string;evaluation_status:string;evaluation?:Evaluation;error?:string}>('/api/attempts',{method:'POST',body:JSON.stringify({session_id:sessionID.value,exercise_id:exercise.value.exercise_id,answer:answer.value})}); lastAttemptID.value=result.attempt_id; if(result.evaluation)evaluation.value=result.evaluation; else{failedAttemptID.value=result.attempt_id;message.value=result.error||'Evaluation failed; the attempt was saved.'} }catch(error){message.value=(error as Error).message}finally{loading.value=false} }
async function reevaluate(){ if(!failedAttemptID.value)return; loading.value=true; try{const result=await api<{evaluation?:Evaluation;error?:string}>(`/api/attempts/${failedAttemptID.value}/reevaluate`,{method:'POST'}); if(result.evaluation){evaluation.value=result.evaluation;failedAttemptID.value=''}else message.value=result.error||'Evaluation failed again.'}catch(error){message.value=(error as Error).message}finally{loading.value=false} }
async function loadHistory(){const params=new URLSearchParams();if(historyScene.value)params.set('scene_id',historyScene.value);if(historySubscene.value)params.set('subscene_id',historySubscene.value);history.value=await api<HistoryItem[]>(`/api/history?${params}`)}
async function loadProgress(){progress.value=await api('/api/progress')} async function loadReviews(){reviews.value=await api('/api/reviews')}
async function changePage(next:string){page.value=next;if(next==='history')await loadHistory();if(next==='progress')await loadProgress();if(next==='review')await loadReviews()}
async function sendFeedback(type:string){if(!exercise.value||!lastAttemptID.value)return;await api('/api/feedback',{method:'POST',body:JSON.stringify({exercise_id:exercise.value.exercise_id,attempt_id:lastAttemptID.value,session_id:sessionID.value,feedback_type:type})})}
function speak(text:string){if(speechSupported.value)speech.speak(text)}
function pct(value:number){return `${Math.round((Number(value)||0)*100)}%`} function masteryClass(m:Mastery){return m.state==='UNKNOWN'?'unknown':m.mastery<.55?'weak':m.mastery>=.8?'strong':'learning'}
const currentSubscene=computed(()=>selectedScene.value?.subscenes.find(item=>item.id===selectedSubsceneID.value)); const verdictText=computed(()=>({correct:'Correct',mostly_correct:'Mostly correct',needs_improvement:'Needs improvement',incorrect:'Keep practicing'} as Record<string,string>)[evaluation.value?.verdict||'']||''); const progressScenes=computed(()=>((progress.value.scene_progress||[]) as Array<any>))
onMounted(async()=>{try{await loadScenes();await nextExercise()}catch(error){message.value=(error as Error).message}})
</script>

<template>
  <div class="shell"><header class="topbar"><button class="brand" @click="changePage('practice')"><span class="brand-mark">EP</span><span><strong>English Practice AI</strong><small>Active expression practice</small></span></button><nav><button v-for="item in [['practice','Practice'],['review','Review'],['scenes','Scenes'],['progress','Progress'],['history','History']]" :key="item[0]" :class="{active:page===item[0]||page==='scene-detail'&&item[0]==='scenes'}" @click="changePage(item[0] as string)">{{item[1]}}</button></nav><span class="status-dot" title="Local mode"></span></header>
  <main>
    <section v-if="page==='practice'" class="practice-page"><div class="eyebrow">{{selectedScene?'SCENE PRACTICE':'DAILY PRACTICE'}}</div><div class="practice-head"><div><h1>Turn ideas into natural English.</h1><p>Write a complete sentence first, then review focused feedback.</p><div v-if="selectedScene" class="context-chip">{{selectedScene.name}}<span v-if="currentSubscene"> · {{currentSubscene.name}}</span><button @click="changePage('scene-detail')">Change</button></div></div><div class="mode-switch"><button v-for="item in [['adaptive','Adaptive'],['weak','Weak areas'],['review','Review']]" :key="item[0]" :class="{selected:mode===item[0]}" @click="mode=item[0] as string;nextExercise()">{{item[1]}}</button></div></div>
      <article v-if="exercise" class="exercise-card"><div class="card-meta"><span>{{exercise.communication_intent||'Communication intent'}}</span><span>Difficulty {{Number(exercise.difficulty||0).toFixed(1)}} / 8</span></div><p class="prompt">{{exercise.chinese_prompt}}</p><div class="target"><span>Target pattern</span><b>{{exercise.target_pattern}}</b></div><textarea v-model="answer" :disabled="!!evaluation" placeholder="Write a complete English sentence…" @keydown.ctrl.enter="submit"></textarea><div class="action-row"><span class="hint">Ctrl + Enter to submit</span><button class="primary" :disabled="loading||!!evaluation||!answer.trim()" @click="submit">{{loading?'Evaluating…':'Submit'}}</button></div><p v-if="exercise.scope_relaxed" class="scope-note">Expanded to a related scope: {{exercise.relaxation_reason}}</p></article>
      <div v-if="loading" class="feedback-card loading-card" aria-live="polite">Evaluating<span class="loading-dots">...</span></div><div v-if="evaluation" class="feedback-card"><div class="feedback-title"><span class="verdict" :class="evaluation.verdict">{{verdictText}}</span><button class="next" @click="nextExercise">Next exercise →</button></div><div class="answer-compare"><div><label>Your answer <button v-if="speechSupported" class="speak-button" @click="speak(answer)" aria-label="Read your answer aloud">🔊</button></label><p>{{answer}}</p></div><div><label>More natural <button v-if="speechSupported" class="speak-button" @click="speak(evaluation!.suggested_answer)" aria-label="Read the suggested answer aloud">🔊</button></label><p class="suggested">{{evaluation.suggested_answer}}</p></div></div><p class="explanation">{{evaluation.explanation_zh}}</p><div class="scores"><div v-for="score in [['Meaning',evaluation.meaning_score],['Grammar',evaluation.grammar_score],['Naturalness',evaluation.naturalness_score],['Pattern',evaluation.pattern_score]]" :key="score[0]" class="score"><span>{{score[0]}}</span><div class="bar"><i :style="{width:`${Number(score[1])*100}%`}"></i></div><b>{{pct(Number(score[1]))}}</b></div></div><div v-if="evaluation.errors.length" class="errors"><div v-for="error in evaluation.errors" :key="error.type" class="error"><span>{{error.type}}</span><p>{{error.explanation}}</p></div></div><div class="feedback-actions"><button @click="sendFeedback('scene_mismatch')">This does not fit the scene</button><button @click="sendFeedback('unnatural')">Prompt feels unnatural</button></div></div><div v-if="message" class="notice-row"><p class="notice">{{message}}</p><button v-if="failedAttemptID" class="secondary" :disabled="loading" @click="reevaluate">Retry evaluation</button></div>
    </section>
    <section v-else-if="page==='scenes'" class="content-page"><div class="eyebrow">SCENES</div><h1>Practice in real-life situations.</h1><p class="lede">Choose a context. The adaptive engine still decides which pattern, review, probe, and difficulty to serve.</p><div class="scene-groups"><div><h2>Recommended and needs attention</h2><div class="scene-grid"><button v-for="scene in scenes.filter(item=>item.mastery.state==='UNKNOWN'||item.mastery.mastery<.7)" :key="scene.id" class="scene-card" @click="openScene(scene.id)"><div class="scene-card-top"><strong>{{scene.name}}</strong><span :class="['state',masteryClass(scene.mastery)]">{{scene.mastery.state==='UNKNOWN'?'New':scene.mastery.state}}</span></div><p>{{scene.description}}</p><div class="scene-meter"><i :style="{width:pct(scene.mastery.mastery)}"></i></div><footer><span>{{pct(scene.mastery.mastery)}} mastery</span><span>{{scene.mastery.weak_subscene_count||0}} needs practice</span></footer></button></div></div><div><h2>Strong contexts</h2><div class="scene-grid"><button v-for="scene in scenes.filter(item=>item.mastery.state!=='UNKNOWN'&&item.mastery.mastery>=.7)" :key="scene.id" class="scene-card" @click="openScene(scene.id)"><div class="scene-card-top"><strong>{{scene.name}}</strong><span class="state strong">Strong</span></div><p>{{scene.description}}</p><div class="scene-meter"><i :style="{width:pct(scene.mastery.mastery)}"></i></div><footer><span>{{pct(scene.mastery.mastery)}} mastery</span><span>{{scene.subscenes.length}} subscenes</span></footer></button></div></div></div></section>
    <section v-else-if="page==='scene-detail'&&selectedScene" class="content-page"><button class="back-link" @click="changePage('scenes')">← All scenes</button><div class="eyebrow">SCENE DETAIL</div><div class="detail-heading"><div><h1>{{selectedScene.name}}</h1><p class="lede">{{selectedScene.description}}</p></div><button class="primary" @click="startPractice(selectedScene.id)">Start adaptive practice</button></div><div class="detail-stats"><div><span>Mastery</span><strong>{{pct(selectedScene.mastery.mastery)}}</strong></div><div><span>Recent accuracy</span><strong>{{pct(selectedScene.mastery.recent_accuracy)}}</strong></div><div><span>Difficulty</span><strong>{{Number(selectedScene.mastery.effective_difficulty||0).toFixed(1)}}</strong></div><div><span>Evidence</span><strong>{{selectedScene.mastery.evidence_count}}</strong></div></div><div class="detail-columns"><div><h2>Subscenes</h2><div class="subscene-list"><button v-for="item in selectedScene.subscenes" :key="item.id" @click="startPractice(selectedScene!.id,item.id)"><span><strong>{{item.name}}</strong><small>{{item.description}}</small></span><b>{{pct(item.mastery.mastery)}} →</b></button></div></div><div><h2>Scene evidence</h2><div class="evidence-card"><div><span>Pattern coverage</span><b>{{pct(selectedScene.mastery.pattern_coverage)}}</b></div><div><span>Intent coverage</span><b>{{pct(selectedScene.mastery.intent_coverage)}}</b></div><div><span>Transfer</span><b>{{pct(selectedScene.mastery.transfer)}}</b></div><div><span>Confidence</span><b>{{pct(selectedScene.mastery.confidence)}}</b></div></div><p class="detail-note">Scene mastery reflects pattern coverage, intent coverage, realized difficulty, recent performance, retention, and cross-scene transfer.</p></div></div></section>
    <section v-else-if="page==='progress'" class="content-page"><div class="eyebrow">PROGRESS</div><h1>See where your expression is growing.</h1><p class="lede">Scene progress is evidence-based and keeps unknown contexts separate from weak ones.</p><div class="stats"><div><span>Validated attempts</span><strong>{{progress.recent_attempts||0}}</strong></div><div><span>Recent success</span><strong>{{pct(progress.recent_success_rate)}}</strong></div><div><span>Global difficulty</span><strong>{{Number(progress.global_difficulty||3).toFixed(1)}}</strong></div></div><h2>Scene progress</h2><div class="progress-list"><button v-for="scene in progressScenes" :key="scene.scene_id" @click="openScene(scene.scene_id)"><span><strong>{{scene.name}}</strong><small>{{scene.state}} · {{scene.evidence_count}} evidence</small></span><div class="bar"><i :style="{width:pct(scene.mastery)}"></i></div><b>{{pct(scene.mastery)}}</b></button></div></section>
    <section v-else-if="page==='history'" class="content-page"><div class="eyebrow">PRACTICE HISTORY</div><h1>Your real expressions.</h1><p class="lede">Filter past attempts by scene or subscene.</p><div class="filter-row"><select v-model="historyScene" @change="historySubscene='';loadHistory()"><option value="">All scenes</option><option v-for="scene in scenes" :key="scene.id" :value="scene.id">{{scene.name}}</option></select><select v-model="historySubscene" @change="loadHistory"><option value="">All subscenes</option><template v-for="scene in scenes" :key="scene.id"><option v-if="scene.id===historyScene" v-for="sub in scene.subscenes" :key="sub.id" :value="sub.id">{{sub.name}}</option></template></select></div><div class="history-list"><article v-for="item in history" :key="item.id" class="history-item"><div class="history-date">{{new Date(item.submitted_at).toLocaleString()}}</div><div><strong>{{item.scene_id}}{{item.subscene_id?' / '+item.subscene_id:''}}</strong><p>{{item.prompt}}</p></div><div class="history-answer">{{item.answer}}</div><span class="pill">{{item.verdict}}</span></article><p v-if="!history.length" class="empty">No practice history yet.</p></div></section>
    <section v-else-if="page==='review'" class="content-page"><div class="eyebrow">REVIEW SCHEDULER</div><h1>Review at the right time.</h1><p class="lede">Reviews continue to use the same adaptive scheduler and scene-aware candidate pool.</p><div class="history-list"><article v-for="item in reviews" :key="item.id" class="history-item"><div class="history-date">{{new Date(item.due_at).toLocaleString()}}</div><strong>{{item.pattern}}</strong><span>{{item.reason}}</span><span class="pill">Priority {{pct(item.priority)}}</span></article><p v-if="!reviews.length" class="empty">Nothing is due for review.</p></div></section>
  </main></div>
</template>
